### ISSUE TITLE
Pagination inside a route

### ISSUE THREAD

**Issue by davibennun** [takeshape/takeshape-routing#5]
Hey guys, 
I have categories and many articles inside each category. I would like to paginate the articles for each category, so route would look like this
/category/:categoryTitle/page-:num

Currently, this is what my tsg.yml looks like:
```
  # Category(ies) page routes
  category:
    path: /category/:categoryTitle/
    template: pages/categories/category.html
    paginate:
      pageSize: 2
      path: /category/page-:num
      firstPage: /categories
      template: pages/categories/category-all.html
      data: data/categories.graphql
      itemName: category

  # Article(s) page routes
  article:
    path: /article/:title/
    template: pages/articles/article.html
    paginate:
      pageSize: 2
      path: /article/page-:num
      firstPage: /articles
      template: pages/articles/article-all.html
      data: data/articles.graphql
      itemName: article
```
With the config like that I can have these routes:
```
/category/justAnotherCategoryTitle
/category/page-2
/categories
/article/justAnotherArticleTitle
/article/page-2
/articles
```
However I would like to be able to paginate the articles inside a particular category:
```
/category/:categoryTitle/page-:num
/category/justAnotherCategoryTitle/page-2 -> would list 2nd page of articles belonging to the category
```
How can I achieve that?
